language: python

python:
  - 2.6
  - 2.7 

env:
  - DJANGO=Django==1.4.5 
  - DJANGO=Django==1.5.1

install:
  - pip install $DJANGO
  - pip install coverage coveralls
  - pip install django-filer>=0.9.5
  - pip install easy-thumbnails>=1.2
  - pip install Markdown>=2.3.1
  - pip install Pillow>=2.1.0

script:
  - coverage run -a setup.py test
  - coverage report

after_success: coveralls
